# Generated by Django 3.2.1 on 2021-05-06 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0005_auto_20210506_0752'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(null=True)),
                ('goal_weight', models.FloatField(null=True)),
                ('calorites_total', models.FloatField(null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('goal_type', models.CharField(choices=[('lose weight', 'lose wight'), ('gain weight', 'gain weight')], max_length=255, null=True)),
                ('weight', models.FloatField(null=True)),
                ('foodlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodlist', to='health.foodlist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
