# Generated by Django 3.2.3 on 2021-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('not active', 'not active'), ('somewhat active', 'somewhat active'), ('medium active', 'medium active'), ('highly active', 'highly active'), ('extremely active', 'extremely active')], max_length=255, null=True),
        ),
    ]
