# Generated by Django 3.2.1 on 2021-05-05 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
                ('meals', models.CharField(choices=[('breakfest', 'breakfest'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=255, null=True)),
                ('meal_name', models.CharField(max_length=50, null=True)),
                ('total_calories', models.FloatField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
