# Generated by Django 3.2.1 on 2021-05-05 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_foodlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(null=True)),
                ('goal_type', models.CharField(choices=[('lose weight', 'lose wight'), ('gain weight', 'gain weight')], max_length=255, null=True)),
                ('goal_weight', models.FloatField(null=True)),
                ('calorites_total', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
