# Generated by Django 3.2.1 on 2021-05-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20210505_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goal_type',
        ),
    ]
