# Generated by Django 3.2.1 on 2021-05-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_remove_profile_goal_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RenameField(
            model_name='foodlist',
            old_name='meals',
            new_name='meal_type',
        ),
    ]
