# Generated by Django 3.2.3 on 2021-05-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_auto_20210515_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='total_carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='foodlist',
            name='total_fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='foodlist',
            name='total_protein',
            field=models.FloatField(null=True),
        ),
    ]
